/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wrapper.core.jni;

public class AddressBook extends Storable {
  private long swigCPtr;

  public AddressBook(long cPtr, boolean cMemoryOwn) {
    super(otapiJNI.AddressBook_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(AddressBook obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_AddressBook(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public long GetContactCount() {
    return otapiJNI.AddressBook_GetContactCount(swigCPtr, this);
  }

  public Contact GetContact(long nIndex) {
    long cPtr = otapiJNI.AddressBook_GetContact(swigCPtr, this, nIndex);
    return (cPtr == 0) ? null : new Contact(cPtr, false);
  }

  public boolean RemoveContact(long nIndex) {
    return otapiJNI.AddressBook_RemoveContact(swigCPtr, this, nIndex);
  }

  public boolean AddContact(Contact disownObject) {
    return otapiJNI.AddressBook_AddContact(swigCPtr, this, Contact.getCPtr(disownObject), disownObject);
  }

  public static AddressBook dynamic_cast(Storable pObject) {
    long cPtr = otapiJNI.AddressBook_dynamic_cast(Storable.getCPtr(pObject), pObject);
    return (cPtr == 0) ? null : new AddressBook(cPtr, false);
  }

}
