// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "BitcoinAcct.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace OTDB {

namespace {

const ::google::protobuf::Descriptor* BitcoinAcct_InternalPB_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BitcoinAcct_InternalPB_reflection_ = NULL;
const ::google::protobuf::Descriptor* Wallet_InternalPB_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Wallet_InternalPB_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_BitcoinAcct_2eproto() {
  protobuf_AddDesc_BitcoinAcct_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "BitcoinAcct.proto");
  GOOGLE_CHECK(file != NULL);
  BitcoinAcct_InternalPB_descriptor_ = file->message_type(0);
  static const int BitcoinAcct_InternalPB_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BitcoinAcct_InternalPB, bitcoin_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BitcoinAcct_InternalPB, bitcoin_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BitcoinAcct_InternalPB, gui_label_),
  };
  BitcoinAcct_InternalPB_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BitcoinAcct_InternalPB_descriptor_,
      BitcoinAcct_InternalPB::default_instance_,
      BitcoinAcct_InternalPB_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BitcoinAcct_InternalPB, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BitcoinAcct_InternalPB, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BitcoinAcct_InternalPB));
  Wallet_InternalPB_descriptor_ = file->message_type(1);
  static const int Wallet_InternalPB_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Wallet_InternalPB, bitcoin_acct_),
  };
  Wallet_InternalPB_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Wallet_InternalPB_descriptor_,
      Wallet_InternalPB::default_instance_,
      Wallet_InternalPB_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Wallet_InternalPB, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Wallet_InternalPB, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Wallet_InternalPB));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_BitcoinAcct_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BitcoinAcct_InternalPB_descriptor_, &BitcoinAcct_InternalPB::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Wallet_InternalPB_descriptor_, &Wallet_InternalPB::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_BitcoinAcct_2eproto() {
  delete BitcoinAcct_InternalPB::default_instance_;
  delete BitcoinAcct_InternalPB_reflection_;
  delete Wallet_InternalPB::default_instance_;
  delete Wallet_InternalPB_reflection_;
}

void protobuf_AddDesc_BitcoinAcct_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021BitcoinAcct.proto\022\004OTDB\"U\n\026BitcoinAcct"
    "_InternalPB\022\022\n\nbitcoin_id\030\001 \001(\t\022\024\n\014bitco"
    "in_name\030\002 \001(\t\022\021\n\tgui_label\030\003 \001(\t\"G\n\021Wall"
    "et_InternalPB\0222\n\014bitcoin_acct\030\001 \003(\0132\034.OT"
    "DB.BitcoinAcct_InternalPB", 185);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "BitcoinAcct.proto", &protobuf_RegisterTypes);
  BitcoinAcct_InternalPB::default_instance_ = new BitcoinAcct_InternalPB();
  Wallet_InternalPB::default_instance_ = new Wallet_InternalPB();
  BitcoinAcct_InternalPB::default_instance_->InitAsDefaultInstance();
  Wallet_InternalPB::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_BitcoinAcct_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_BitcoinAcct_2eproto {
  StaticDescriptorInitializer_BitcoinAcct_2eproto() {
    protobuf_AddDesc_BitcoinAcct_2eproto();
  }
} static_descriptor_initializer_BitcoinAcct_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int BitcoinAcct_InternalPB::kBitcoinIdFieldNumber;
const int BitcoinAcct_InternalPB::kBitcoinNameFieldNumber;
const int BitcoinAcct_InternalPB::kGuiLabelFieldNumber;
#endif  // !_MSC_VER

BitcoinAcct_InternalPB::BitcoinAcct_InternalPB()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void BitcoinAcct_InternalPB::InitAsDefaultInstance() {
}

BitcoinAcct_InternalPB::BitcoinAcct_InternalPB(const BitcoinAcct_InternalPB& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void BitcoinAcct_InternalPB::SharedCtor() {
  _cached_size_ = 0;
  bitcoin_id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  bitcoin_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  gui_label_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BitcoinAcct_InternalPB::~BitcoinAcct_InternalPB() {
  SharedDtor();
}

void BitcoinAcct_InternalPB::SharedDtor() {
  if (bitcoin_id_ != &::google::protobuf::internal::kEmptyString) {
    delete bitcoin_id_;
  }
  if (bitcoin_name_ != &::google::protobuf::internal::kEmptyString) {
    delete bitcoin_name_;
  }
  if (gui_label_ != &::google::protobuf::internal::kEmptyString) {
    delete gui_label_;
  }
  if (this != default_instance_) {
  }
}

void BitcoinAcct_InternalPB::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BitcoinAcct_InternalPB::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BitcoinAcct_InternalPB_descriptor_;
}

const BitcoinAcct_InternalPB& BitcoinAcct_InternalPB::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_BitcoinAcct_2eproto();  return *default_instance_;
}

BitcoinAcct_InternalPB* BitcoinAcct_InternalPB::default_instance_ = NULL;

BitcoinAcct_InternalPB* BitcoinAcct_InternalPB::New() const {
  return new BitcoinAcct_InternalPB;
}

void BitcoinAcct_InternalPB::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_bitcoin_id()) {
      if (bitcoin_id_ != &::google::protobuf::internal::kEmptyString) {
        bitcoin_id_->clear();
      }
    }
    if (has_bitcoin_name()) {
      if (bitcoin_name_ != &::google::protobuf::internal::kEmptyString) {
        bitcoin_name_->clear();
      }
    }
    if (has_gui_label()) {
      if (gui_label_ != &::google::protobuf::internal::kEmptyString) {
        gui_label_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BitcoinAcct_InternalPB::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string bitcoin_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_bitcoin_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->bitcoin_id().data(), this->bitcoin_id().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_bitcoin_name;
        break;
      }
      
      // optional string bitcoin_name = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_bitcoin_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_bitcoin_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->bitcoin_name().data(), this->bitcoin_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_gui_label;
        break;
      }
      
      // optional string gui_label = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_gui_label:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_gui_label()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->gui_label().data(), this->gui_label().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BitcoinAcct_InternalPB::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string bitcoin_id = 1;
  if (has_bitcoin_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->bitcoin_id().data(), this->bitcoin_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->bitcoin_id(), output);
  }
  
  // optional string bitcoin_name = 2;
  if (has_bitcoin_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->bitcoin_name().data(), this->bitcoin_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->bitcoin_name(), output);
  }
  
  // optional string gui_label = 3;
  if (has_gui_label()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->gui_label().data(), this->gui_label().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->gui_label(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* BitcoinAcct_InternalPB::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string bitcoin_id = 1;
  if (has_bitcoin_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->bitcoin_id().data(), this->bitcoin_id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->bitcoin_id(), target);
  }
  
  // optional string bitcoin_name = 2;
  if (has_bitcoin_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->bitcoin_name().data(), this->bitcoin_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->bitcoin_name(), target);
  }
  
  // optional string gui_label = 3;
  if (has_gui_label()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->gui_label().data(), this->gui_label().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->gui_label(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int BitcoinAcct_InternalPB::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string bitcoin_id = 1;
    if (has_bitcoin_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->bitcoin_id());
    }
    
    // optional string bitcoin_name = 2;
    if (has_bitcoin_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->bitcoin_name());
    }
    
    // optional string gui_label = 3;
    if (has_gui_label()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->gui_label());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BitcoinAcct_InternalPB::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BitcoinAcct_InternalPB* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BitcoinAcct_InternalPB*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BitcoinAcct_InternalPB::MergeFrom(const BitcoinAcct_InternalPB& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_bitcoin_id()) {
      set_bitcoin_id(from.bitcoin_id());
    }
    if (from.has_bitcoin_name()) {
      set_bitcoin_name(from.bitcoin_name());
    }
    if (from.has_gui_label()) {
      set_gui_label(from.gui_label());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BitcoinAcct_InternalPB::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BitcoinAcct_InternalPB::CopyFrom(const BitcoinAcct_InternalPB& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BitcoinAcct_InternalPB::IsInitialized() const {
  
  return true;
}

void BitcoinAcct_InternalPB::Swap(BitcoinAcct_InternalPB* other) {
  if (other != this) {
    std::swap(bitcoin_id_, other->bitcoin_id_);
    std::swap(bitcoin_name_, other->bitcoin_name_);
    std::swap(gui_label_, other->gui_label_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BitcoinAcct_InternalPB::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BitcoinAcct_InternalPB_descriptor_;
  metadata.reflection = BitcoinAcct_InternalPB_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Wallet_InternalPB::kBitcoinAcctFieldNumber;
#endif  // !_MSC_VER

Wallet_InternalPB::Wallet_InternalPB()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Wallet_InternalPB::InitAsDefaultInstance() {
}

Wallet_InternalPB::Wallet_InternalPB(const Wallet_InternalPB& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Wallet_InternalPB::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Wallet_InternalPB::~Wallet_InternalPB() {
  SharedDtor();
}

void Wallet_InternalPB::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Wallet_InternalPB::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Wallet_InternalPB::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Wallet_InternalPB_descriptor_;
}

const Wallet_InternalPB& Wallet_InternalPB::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_BitcoinAcct_2eproto();  return *default_instance_;
}

Wallet_InternalPB* Wallet_InternalPB::default_instance_ = NULL;

Wallet_InternalPB* Wallet_InternalPB::New() const {
  return new Wallet_InternalPB;
}

void Wallet_InternalPB::Clear() {
  bitcoin_acct_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Wallet_InternalPB::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .OTDB.BitcoinAcct_InternalPB bitcoin_acct = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_bitcoin_acct:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_bitcoin_acct()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_bitcoin_acct;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Wallet_InternalPB::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .OTDB.BitcoinAcct_InternalPB bitcoin_acct = 1;
  for (int i = 0; i < this->bitcoin_acct_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->bitcoin_acct(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Wallet_InternalPB::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .OTDB.BitcoinAcct_InternalPB bitcoin_acct = 1;
  for (int i = 0; i < this->bitcoin_acct_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->bitcoin_acct(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Wallet_InternalPB::ByteSize() const {
  int total_size = 0;
  
  // repeated .OTDB.BitcoinAcct_InternalPB bitcoin_acct = 1;
  total_size += 1 * this->bitcoin_acct_size();
  for (int i = 0; i < this->bitcoin_acct_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->bitcoin_acct(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Wallet_InternalPB::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Wallet_InternalPB* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Wallet_InternalPB*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Wallet_InternalPB::MergeFrom(const Wallet_InternalPB& from) {
  GOOGLE_CHECK_NE(&from, this);
  bitcoin_acct_.MergeFrom(from.bitcoin_acct_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Wallet_InternalPB::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Wallet_InternalPB::CopyFrom(const Wallet_InternalPB& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Wallet_InternalPB::IsInitialized() const {
  
  return true;
}

void Wallet_InternalPB::Swap(Wallet_InternalPB* other) {
  if (other != this) {
    bitcoin_acct_.Swap(&other->bitcoin_acct_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Wallet_InternalPB::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Wallet_InternalPB_descriptor_;
  metadata.reflection = Wallet_InternalPB_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace OTDB

// @@protoc_insertion_point(global_scope)
