/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wrapper.core.jni;

public class Contact extends Displayable {
  private long swigCPtr;

  public Contact(long cPtr, boolean cMemoryOwn) {
    super(otapiJNI.Contact_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Contact obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_Contact(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setContact_id(String value) {
    otapiJNI.Contact_contact_id_set(swigCPtr, this, value);
  }

  public String getContact_id() {
    return otapiJNI.Contact_contact_id_get(swigCPtr, this);
  }

  public void setEmail(String value) {
    otapiJNI.Contact_email_set(swigCPtr, this, value);
  }

  public String getEmail() {
    return otapiJNI.Contact_email_get(swigCPtr, this);
  }

  public void setMemo(String value) {
    otapiJNI.Contact_memo_set(swigCPtr, this, value);
  }

  public String getMemo() {
    return otapiJNI.Contact_memo_get(swigCPtr, this);
  }

  public void setPublic_key(String value) {
    otapiJNI.Contact_public_key_set(swigCPtr, this, value);
  }

  public String getPublic_key() {
    return otapiJNI.Contact_public_key_get(swigCPtr, this);
  }

}
