/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wrapper.core.jni;

public class OfferDataMarket extends Displayable {
  private long swigCPtr;

  public OfferDataMarket(long cPtr, boolean cMemoryOwn) {
    super(otapiJNI.OfferDataMarket_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(OfferDataMarket obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_OfferDataMarket(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }
/*@SWIG:OTAPI.i,387,OT_CAN_BE_CONTAINED_BY@*/
	// Ensure that the GC doesn't collect any OT_CONTAINER instance set from Java
	private OfferListMarket containerRefOfferListMarket;
	// ----------------	
	protected void addReference(OfferListMarket theContainer) {  // This is Java code
		containerRefOfferListMarket = theContainer;
	}
	// ----------------
/*@SWIG@*/
	// ------------------------
  public void setGui_label(String value) {
    otapiJNI.OfferDataMarket_gui_label_set(swigCPtr, this, value);
  }

  public String getGui_label() {
    return otapiJNI.OfferDataMarket_gui_label_get(swigCPtr, this);
  }

  public void setTransaction_id(SWIGTYPE_p_uint64_t value) {
    otapiJNI.OfferDataMarket_transaction_id_set(swigCPtr, this, SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint64_t getTransaction_id() {
    return new SWIGTYPE_p_uint64_t(otapiJNI.OfferDataMarket_transaction_id_get(swigCPtr, this), true);
  }

  public void setPrice_per_scale(SWIGTYPE_p_uint64_t value) {
    otapiJNI.OfferDataMarket_price_per_scale_set(swigCPtr, this, SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint64_t getPrice_per_scale() {
    return new SWIGTYPE_p_uint64_t(otapiJNI.OfferDataMarket_price_per_scale_get(swigCPtr, this), true);
  }

  public void setAvailable_assets(SWIGTYPE_p_uint64_t value) {
    otapiJNI.OfferDataMarket_available_assets_set(swigCPtr, this, SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint64_t getAvailable_assets() {
    return new SWIGTYPE_p_uint64_t(otapiJNI.OfferDataMarket_available_assets_get(swigCPtr, this), true);
  }

  public void setMinimum_increment(SWIGTYPE_p_uint64_t value) {
    otapiJNI.OfferDataMarket_minimum_increment_set(swigCPtr, this, SWIGTYPE_p_uint64_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint64_t getMinimum_increment() {
    return new SWIGTYPE_p_uint64_t(otapiJNI.OfferDataMarket_minimum_increment_get(swigCPtr, this), true);
  }

  public static OfferDataMarket ot_dynamic_cast(Storable pObject) {
    long cPtr = otapiJNI.OfferDataMarket_ot_dynamic_cast(Storable.getCPtr(pObject), pObject);
    return (cPtr == 0) ? null : new OfferDataMarket(cPtr, false);
  }

}
