# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.

package OTAPI;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package OTAPIc;
bootstrap OTAPI;
package OTAPI;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package OTAPI;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package OTAPI;

*OT_API_Init = *OTAPIc::OT_API_Init;
*OT_API_loadWallet = *OTAPIc::OT_API_loadWallet;
*OT_API_connectServer = *OTAPIc::OT_API_connectServer;
*OT_API_processSockets = *OTAPIc::OT_API_processSockets;
*OT_API_checkServerID = *OTAPIc::OT_API_checkServerID;
*OT_API_createUserAccount = *OTAPIc::OT_API_createUserAccount;
*OT_API_checkUser = *OTAPIc::OT_API_checkUser;
*OT_API_getRequest = *OTAPIc::OT_API_getRequest;
*OT_API_issueAssetType = *OTAPIc::OT_API_issueAssetType;
*OT_API_getContract = *OTAPIc::OT_API_getContract;
*OT_API_getMint = *OTAPIc::OT_API_getMint;
*OT_API_createAssetAccount = *OTAPIc::OT_API_createAssetAccount;
*OT_API_getAccount = *OTAPIc::OT_API_getAccount;
*OT_API_issueBasket = *OTAPIc::OT_API_issueBasket;
*OT_API_exchangeBasket = *OTAPIc::OT_API_exchangeBasket;
*OT_API_getTransactionNumber = *OTAPIc::OT_API_getTransactionNumber;
*OT_API_notarizeWithdrawal = *OTAPIc::OT_API_notarizeWithdrawal;
*OT_API_notarizeDeposit = *OTAPIc::OT_API_notarizeDeposit;
*OT_API_notarizeTransfer = *OTAPIc::OT_API_notarizeTransfer;
*OT_API_getInbox = *OTAPIc::OT_API_getInbox;
*OT_API_processInbox = *OTAPIc::OT_API_processInbox;
*OT_API_withdrawVoucher = *OTAPIc::OT_API_withdrawVoucher;
*OT_API_depositCheque = *OTAPIc::OT_API_depositCheque;
*OT_API_getNymCount = *OTAPIc::OT_API_getNymCount;
*OT_API_getServerCount = *OTAPIc::OT_API_getServerCount;
*OT_API_getAssetTypeCount = *OTAPIc::OT_API_getAssetTypeCount;
*OT_API_getAccountCount = *OTAPIc::OT_API_getAccountCount;
*OT_API_getNym = *OTAPIc::OT_API_getNym;
*OT_API_getServer = *OTAPIc::OT_API_getServer;
*OT_API_getAssetType = *OTAPIc::OT_API_getAssetType;
*OT_API_GetAccountWallet = *OTAPIc::OT_API_GetAccountWallet;

# ------- VARIABLE STUBS --------

package OTAPI;

1;
