/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class OTAPIJNI {
  public final static native int OT_API_Init(String jarg1);
  public final static native int OT_API_LoadWallet(String jarg1);
  public final static native int OT_API_connectServer(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native int OT_API_processSockets();
  public final static native void OT_API_checkServerID(String jarg1, String jarg2);
  public final static native void OT_API_createUserAccount(String jarg1, String jarg2);
  public final static native void OT_API_checkUser(String jarg1, String jarg2, String jarg3);
  public final static native void OT_API_getRequest(String jarg1, String jarg2);
  public final static native void OT_API_issueAssetType(String jarg1, String jarg2, String jarg3);
  public final static native void OT_API_getContract(String jarg1, String jarg2, String jarg3);
  public final static native void OT_API_getMint(String jarg1, String jarg2, String jarg3);
  public final static native void OT_API_createAssetAccount(String jarg1, String jarg2, String jarg3);
  public final static native void OT_API_getAccount(String jarg1, String jarg2, String jarg3);
  public final static native void OT_API_issueBasket(String jarg1, String jarg2, String jarg3);
  public final static native void OT_API_exchangeBasket(String jarg1, String jarg2, String jarg3, String jarg4);
  public final static native void OT_API_getTransactionNumber(String jarg1, String jarg2);
  public final static native void OT_API_notarizeWithdrawal(String jarg1, String jarg2, String jarg3, String jarg4);
  public final static native void OT_API_notarizeDeposit(String jarg1, String jarg2, String jarg3, String jarg4);
  public final static native void OT_API_notarizeTransfer(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6);
  public final static native void OT_API_getInbox(String jarg1, String jarg2, String jarg3);
  public final static native void OT_API_processInbox(String jarg1, String jarg2, String jarg3, String jarg4);
  public final static native void OT_API_withdrawVoucher(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6);
  public final static native void OT_API_depositCheque(String jarg1, String jarg2, String jarg3, String jarg4);
  public final static native int OT_API_GetNymCount();
  public final static native int OT_API_GetServerCount();
  public final static native int OT_API_GetAssetTypeCount();
  public final static native int OT_API_GetAccountCount();
  public final static native String OT_API_GetNym_ID(int jarg1);
  public final static native String OT_API_GetNym_Name(String jarg1);
  public final static native String OT_API_GetServer_ID(int jarg1);
  public final static native String OT_API_GetServer_Name(String jarg1);
  public final static native String OT_API_GetAssetType_ID(int jarg1);
  public final static native String OT_API_GetAssetType_Name(String jarg1);
  public final static native String OT_API_GetAccountWallet_ID(int jarg1);
  public final static native String OT_API_GetAccountWallet_Name(String jarg1);
}
