/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_OTAPI_H
#define PHP_OTAPI_H

extern zend_module_entry otapi_module_entry;
#define phpext_otapi_ptr &otapi_module_entry

#ifdef PHP_WIN32
# define PHP_OTAPI_API __declspec(dllexport)
#else
# define PHP_OTAPI_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(otapi);
PHP_MSHUTDOWN_FUNCTION(otapi);
PHP_RINIT_FUNCTION(otapi);
PHP_RSHUTDOWN_FUNCTION(otapi);
PHP_MINFO_FUNCTION(otapi);

ZEND_NAMED_FUNCTION(_wrap_OT_API_Init);
ZEND_NAMED_FUNCTION(_wrap_OT_API_LoadWallet);
ZEND_NAMED_FUNCTION(_wrap_OT_API_SwitchWallet);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetMemlogSize);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetMemlogAtIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_PeekMemlogFront);
ZEND_NAMED_FUNCTION(_wrap_OT_API_PeekMemlogBack);
ZEND_NAMED_FUNCTION(_wrap_OT_API_PopMemlogFront);
ZEND_NAMED_FUNCTION(_wrap_OT_API_PopMemlogBack);
ZEND_NAMED_FUNCTION(_wrap_OT_API_CreateNym);
ZEND_NAMED_FUNCTION(_wrap_OT_API_AddServerContract);
ZEND_NAMED_FUNCTION(_wrap_OT_API_AddAssetContract);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetServerCount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetAssetTypeCount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetAccountCount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNymCount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetServer_ID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetServer_Name);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetAssetType_ID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetAssetType_Name);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetAccountWallet_ID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetAccountWallet_Name);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetAccountWallet_Balance);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetAccountWallet_Type);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetAccountWallet_AssetTypeID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetAccountWallet_ServerID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetAccountWallet_NymID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_VerifyAccountReceipt);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNym_TransactionNumCount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNym_ID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNym_Name);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNym_Stats);
ZEND_NAMED_FUNCTION(_wrap_OT_API_IsNym_RegisteredAtServer);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNym_MailCount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNym_MailContentsByIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNym_MailSenderIDByIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNym_MailServerIDByIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Nym_RemoveMailByIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Nym_VerifyMailByIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNym_OutmailCount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNym_OutmailContentsByIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNym_OutmailRecipientIDByIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GetNym_OutmailServerIDByIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Nym_RemoveOutmailByIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Nym_VerifyOutmailByIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Wallet_CanRemoveServer);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Wallet_RemoveServer);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Wallet_CanRemoveAssetType);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Wallet_RemoveAssetType);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Wallet_CanRemoveNym);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Wallet_RemoveNym);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Wallet_CanRemoveAccount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Wallet_RemoveAccount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Wallet_ImportNym);
ZEND_NAMED_FUNCTION(_wrap_OT_API_SetNym_Name);
ZEND_NAMED_FUNCTION(_wrap_OT_API_SetAccountWallet_Name);
ZEND_NAMED_FUNCTION(_wrap_OT_API_SetAssetType_Name);
ZEND_NAMED_FUNCTION(_wrap_OT_API_SetServer_Name);
ZEND_NAMED_FUNCTION(_wrap_OT_API_VerifyAndRetrieveXMLContents);
ZEND_NAMED_FUNCTION(_wrap_OT_API_WriteCheque);
ZEND_NAMED_FUNCTION(_wrap_OT_API_WritePaymentPlan);
ZEND_NAMED_FUNCTION(_wrap_OT_API_LoadUserPubkey);
ZEND_NAMED_FUNCTION(_wrap_OT_API_LoadPubkey);
ZEND_NAMED_FUNCTION(_wrap_OT_API_VerifyUserPrivateKey);
ZEND_NAMED_FUNCTION(_wrap_OT_API_LoadPurse);
ZEND_NAMED_FUNCTION(_wrap_OT_API_LoadMint);
ZEND_NAMED_FUNCTION(_wrap_OT_API_LoadAssetContract);
ZEND_NAMED_FUNCTION(_wrap_OT_API_LoadServerContract);
ZEND_NAMED_FUNCTION(_wrap_OT_API_IsBasketCurrency);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Basket_GetMemberCount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Basket_GetMemberType);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Basket_GetMinimumTransferAmount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Basket_GetMemberMinimumTransferAmount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_LoadAssetAccount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_LoadInbox);
ZEND_NAMED_FUNCTION(_wrap_OT_API_LoadOutbox);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Ledger_GetCount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Ledger_CreateResponse);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Ledger_GetTransactionByIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Ledger_GetTransactionByID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Ledger_GetTransactionIDByIndex);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Ledger_AddTransaction);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Transaction_CreateResponse);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Ledger_FinalizeResponse);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Transaction_GetType);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Transaction_GetVoucher);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Transaction_GetSuccess);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Transaction_GetDateSigned);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Transaction_GetAmount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Pending_GetNote);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Transaction_GetSenderUserID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Transaction_GetSenderAcctID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Transaction_GetRecipientUserID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Transaction_GetRecipientAcctID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Transaction_GetDisplayReferenceToNum);
ZEND_NAMED_FUNCTION(_wrap_OT_API_CreatePurse);
ZEND_NAMED_FUNCTION(_wrap_OT_API_SavePurse);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Purse_GetTotalValue);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Purse_Count);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Purse_Peek);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Purse_Pop);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Purse_Push);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Wallet_ImportPurse);
ZEND_NAMED_FUNCTION(_wrap_OT_API_exchangePurse);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Token_ChangeOwner);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Token_GetID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Token_GetDenomination);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Token_GetSeries);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Token_GetValidFrom);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Token_GetValidTo);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Token_GetAssetID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Token_GetServerID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_checkServerID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_createUserAccount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_checkUser);
ZEND_NAMED_FUNCTION(_wrap_OT_API_sendUserMessage);
ZEND_NAMED_FUNCTION(_wrap_OT_API_getRequest);
ZEND_NAMED_FUNCTION(_wrap_OT_API_getTransactionNumber);
ZEND_NAMED_FUNCTION(_wrap_OT_API_issueAssetType);
ZEND_NAMED_FUNCTION(_wrap_OT_API_getContract);
ZEND_NAMED_FUNCTION(_wrap_OT_API_getMint);
ZEND_NAMED_FUNCTION(_wrap_OT_API_createAssetAccount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_getAccount);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GenerateBasketCreation);
ZEND_NAMED_FUNCTION(_wrap_OT_API_AddBasketCreationItem);
ZEND_NAMED_FUNCTION(_wrap_OT_API_issueBasket);
ZEND_NAMED_FUNCTION(_wrap_OT_API_GenerateBasketExchange);
ZEND_NAMED_FUNCTION(_wrap_OT_API_AddBasketExchangeItem);
ZEND_NAMED_FUNCTION(_wrap_OT_API_exchangeBasket);
ZEND_NAMED_FUNCTION(_wrap_OT_API_notarizeWithdrawal);
ZEND_NAMED_FUNCTION(_wrap_OT_API_notarizeDeposit);
ZEND_NAMED_FUNCTION(_wrap_OT_API_notarizeTransfer);
ZEND_NAMED_FUNCTION(_wrap_OT_API_getInbox);
ZEND_NAMED_FUNCTION(_wrap_OT_API_getOutbox);
ZEND_NAMED_FUNCTION(_wrap_OT_API_getNymbox);
ZEND_NAMED_FUNCTION(_wrap_OT_API_LoadNymbox);
ZEND_NAMED_FUNCTION(_wrap_OT_API_processInbox);
ZEND_NAMED_FUNCTION(_wrap_OT_API_processNymbox);
ZEND_NAMED_FUNCTION(_wrap_OT_API_withdrawVoucher);
ZEND_NAMED_FUNCTION(_wrap_OT_API_depositCheque);
ZEND_NAMED_FUNCTION(_wrap_OT_API_depositPaymentPlan);
ZEND_NAMED_FUNCTION(_wrap_OT_API_issueMarketOffer);
ZEND_NAMED_FUNCTION(_wrap_OT_API_PopMessageBuffer);
ZEND_NAMED_FUNCTION(_wrap_OT_API_FlushMessageBuffer);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Message_GetCommand);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Message_GetSuccess);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Message_GetTransactionSuccess);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Message_GetLedger);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Message_GetNewAssetTypeID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Message_GetNewIssuerAcctID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Message_GetNewAcctID);
ZEND_NAMED_FUNCTION(_wrap_OT_API_ConnectServer);
ZEND_NAMED_FUNCTION(_wrap_OT_API_ProcessSockets);
ZEND_NAMED_FUNCTION(_wrap_new_OTCallback);
ZEND_NAMED_FUNCTION(_wrap_OTCallback_run1);
ZEND_NAMED_FUNCTION(_wrap_OTCallback_run2);
ZEND_NAMED_FUNCTION(_wrap_new_OTCaller);
ZEND_NAMED_FUNCTION(_wrap_OTCaller_GetPassword);
ZEND_NAMED_FUNCTION(_wrap_OTCaller_delCallback);
ZEND_NAMED_FUNCTION(_wrap_OTCaller_setCallback);
ZEND_NAMED_FUNCTION(_wrap_OTCaller_isCallbackSet);
ZEND_NAMED_FUNCTION(_wrap_OTCaller_call1);
ZEND_NAMED_FUNCTION(_wrap_OTCaller_call2);
ZEND_NAMED_FUNCTION(_wrap_OT_API_Set_PasswordCallback);
#endif /* PHP_OTAPI_H */
