/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wrapper.core.jni;

public class Server extends ServerInfo {
  private long swigCPtr;

  public Server(long cPtr, boolean cMemoryOwn) {
    super(otapiJNI.Server_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Server obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_Server(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setServer_host(String value) {
    otapiJNI.Server_server_host_set(swigCPtr, this, value);
  }

  public String getServer_host() {
    return otapiJNI.Server_server_host_get(swigCPtr, this);
  }

  public void setServer_port(String value) {
    otapiJNI.Server_server_port_set(swigCPtr, this, value);
  }

  public String getServer_port() {
    return otapiJNI.Server_server_port_get(swigCPtr, this);
  }

}
