/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.3
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wrapper.core.jni;

public class WalletData extends Storable {
  private long swigCPtr;

  public WalletData(long cPtr, boolean cMemoryOwn) {
    super(otapiJNI.WalletData_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(WalletData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_WalletData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public long GetBitcoinServerCount() {
    return otapiJNI.WalletData_GetBitcoinServerCount(swigCPtr, this);
  }

  public BitcoinServer GetBitcoinServer(long nIndex) {
    long cPtr = otapiJNI.WalletData_GetBitcoinServer(swigCPtr, this, nIndex);
    return (cPtr == 0) ? null : new BitcoinServer(cPtr, false);
  }

  public boolean RemoveBitcoinServer(long nIndex) {
    return otapiJNI.WalletData_RemoveBitcoinServer(swigCPtr, this, nIndex);
  }

  public boolean AddBitcoinServer(BitcoinServer disownObject) {
    return otapiJNI.WalletData_AddBitcoinServer(swigCPtr, this, BitcoinServer.getCPtr(disownObject), disownObject);
  }

  public long GetBitcoinAcctCount() {
    return otapiJNI.WalletData_GetBitcoinAcctCount(swigCPtr, this);
  }

  public BitcoinAcct GetBitcoinAcct(long nIndex) {
    long cPtr = otapiJNI.WalletData_GetBitcoinAcct(swigCPtr, this, nIndex);
    return (cPtr == 0) ? null : new BitcoinAcct(cPtr, false);
  }

  public boolean RemoveBitcoinAcct(long nIndex) {
    return otapiJNI.WalletData_RemoveBitcoinAcct(swigCPtr, this, nIndex);
  }

  public boolean AddBitcoinAcct(BitcoinAcct disownObject) {
    return otapiJNI.WalletData_AddBitcoinAcct(swigCPtr, this, BitcoinAcct.getCPtr(disownObject), disownObject);
  }

  public static WalletData dynamic_cast(Storable pObject) {
    long cPtr = otapiJNI.WalletData_dynamic_cast(Storable.getCPtr(pObject), pObject);
    return (cPtr == 0) ? null : new WalletData(cPtr, false);
  }

}
